WebBanVeXemPhim/Webanvexemphim/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webanvexemphim.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LienHe()
        {
            return View();
        }
        
    }
}

WebBanVeXemPhim/Webanvexemphim/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webanvexemphim.Controllers
{
    public class ModulesController : Controller
    {
        private Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
        // GET: nơi chứa các layout chính của web header/footer
        public ActionResult _header()
        {
            return View("_header");
        }
        public ActionResult _mainmenu()
        {
            var listParentCate = db.menus.Where(m => m.status == 1 && m.parentid == 0).OrderBy(m => m.orders).ToList();
            return View("_mainmenu", listParentCate);
        }
        public ActionResult _footer()
        {
            return View("_footer");
        }

        public ActionResult submainmenu(int id)
        {
            ViewBag.mainmenuitem = db.menus.Find(id);
            var list = db.menus.Where(m => m.status == 1).Where(m => m.parentid == id)
                .OrderBy(m => m.orders);
            if (list.Count() != 0)
            {
                return View("_submainmenu1", list);
            }
            else
            {
                return View("_submainmenu2");
            }

        }

    }
}

WebBanVeXemPhim/Webanvexemphim/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webanvexemphim.Controllers
{
    public class MoviesController : Controller
    {
        private Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
        // GET: Movies all movie
        public ActionResult Index()
        {
            return View();
        }
        //movies detail
        public ActionResult MoviesDetail(string slug)
        {
            var singleMovies = db.movies.Where(m => m.status == 1 && m.slug==slug ).FirstOrDefault();
            return View("MoviesDetail",singleMovies);
        }
        public ActionResult Movie_Category(string slug)
        {
            var singleMovies = db.categories.Where(m => m.status == 1 && m.slug == slug).FirstOrDefault();
            ViewBag.nameCate = singleMovies.name;
            var listMovie = db.movies.Where(m => m.status == 1 && m.catid== singleMovies.ID).ToList();
            return View("Movie_Category", listMovie);
        }
       
        // layout main
        public ActionResult _movieSlider()
        {
            return View("_movieSlider");
        }
        public ActionResult _movieComingSoom()
        {
            return View("_movieComingSoom");
        }
        // single List Movie
        public ActionResult _SingleMovie()
        {
            return View("_SingleMovie");
        }

        // pages main
        public ActionResult movieDetail()
        {
            return View("_SingleMovie");
        }

        //
        public ActionResult _MovieActive()
        {
            var list = db.movies.Where(m => m.status == 1).ToList();
            return View("_MovieActive", list);
        }
        public ActionResult _MovieOfDay()
        {
            var list = db.movies.Where(m => m.status == 1).ToList();
            return View("_MovieOfDay", list);
        }

    }
}

WebBanVeXemPhim/Webanvexemphim/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.Action("_Header", "Modules")
<section class="section-text-white position-relative">
    <div class="d-background" data-image-src="http://via.placeholder.com/1920x1080" data-parallax="scroll"></div>
    <div class="d-background bg-theme-blacked"></div>
    <div class="mt-auto container position-relative">
        <div class="top-block-head text-uppercase">

        </div>
        <div class="top-block-footer">
            <div class="slick-spaced slick-carousel" data-slick-view="navigation responsive-4">


                @Html.Action("_MovieActive", "Movies")


                <div class="slick-arrows">
                    <div class="slick-arrow-prev">
                        <span class="th-dots th-arrow-left th-dots-animated">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                    <div class="slick-arrow-next">
                        <span class="th-dots th-arrow-right th-dots-animated">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="section-head-img"><img src="~/Public/images/parts/movie.png" /></div>
<div class="section-head">
    <h2 class="section-title text-uppercase">PHIM TẠI RẠP</h2>
    @*<p class="section-text">@DateTime.Now.ToString("dd/MM/yyyy")</p>*@
</div>
<section class="section-long">
    <div class="container">
        <!--<div class="section-head">
            <h2 class="section-title text-uppercase">PHIM ĐANG CHIẾU</h2>-->
        @*<p class="section-text">@DateTime.Now.ToString("dd/MM/yyyy")</p>*@
        <!--</div>-->
        @Html.Action("_MovieOfDay", "Movies")
    </div>
</section>


<a class="scroll-top disabled" href="#"><i class="fas fa-angle-up" aria-hidden="true"></i></a>
@Html.Action("_footer", "Modules")

WebBanVeXemPhim/Webanvexemphim/Views/Home/LienHe.cshtml
@{
    ViewBag.Title = "LienHe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Action("_Header", "Modules")
<section>
    <div class="gmap-with-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.569194260589!2d106.7602581147495!3d10.844243492275536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317527c07e1c02bf%3A0x36e3b562c0d4a5a!2sLotte%20Cinema%20Moonlight!5e0!3m2!1svi!2s!4v1624025454789!5m2!1svi!2s" width="100%" height="700rem" style="border:0; position: absolute; z-index: 0" allowfullscreen="" loading="lazy"></iframe>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 ml-lg-auto">
                    <div class="gmap-form ">

                        <h4 style="color: white" class="form-title text-uppercase">
                            Thông tin liên hệ
                        </h4>
                        
                        <form autocomplete="off">
                            <div class="row form-grid">
                                <div class="col-sm-6">
                                    <div class="input-view-flat input-group">
                                        <input class="form-control" name="name" type="text" placeholder="Tên bạn" />
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="input-view-flat input-group">
                                        <input class="form-control" name="email" type="email" placeholder="Email" />
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="input-view-flat input-group">
                                        <textarea class="form-control" name="message" placeholder="Lời nhắn"></textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="px-5 btn btn-theme" type="submit">Gửi liên hệ</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-long">
    <div class="container">
        <div class="grid row">
            <div class="col-md-6">
                <h4 class="entity-title">Địa chỉ</h4>
                <p class="entity-text">
                    102 Đặng Văn Bi, thành phố Thủ Đức, TP.HCM
                    VIỆT NAM
                </p>
            </div>
            <div class="col-md-6">
                <h4 class="entity-title">Số điện thoại</h4>
                <p class="entity-text">
                    (+88) 018 12346251, (+43) 018 4321 6789
                    <br />(+50) 113 1346 7654, (+08) 555 456 7890
                </p>
            </div>
            <div class="col-md-6">
                <h4 class="entity-title">Email</h4>
                <p class="entity-text">
                    a@gmail.com
                    <br />a@gmail.com
                </p>
            </div>
            <div class="col-md-6">
                <h4 class="entity-title">Fax</h4>
                <p class="entity-text">
                    (+88) 018 12346251, (+43) 018 4321 6789
                    <br />(+50) 113 1346 7654, (+08) 555 456 7890
                </p>
            </div>
        </div>
     
    </div>
  
</section>