WebBanVeXemPhim/Webanvexemphim/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webanvexemphim.Models;

namespace Webanvexemphim.Controllers
{
    public class CartController : Controller
    {
        
            // khởi tạo session:
            private const string SessionCart = "SessionCart";
        // GET: Cart
            Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
            public ActionResult Index()
            {
                var cart = Session[SessionCart];
                var list = new List<Cart_item>();
                if (cart != null)
                {
                    list = (List<Cart_item>)cart;
                }
                return View(list);
            }
            public ActionResult card_header()
            {
                var cart = Session[SessionCart];
                var list = new List<Cart_item>();
                if (cart != null)
                {

                    list = (List<Cart_item>)cart;
                    int quantytyyy = 0;
                    foreach (var item1 in list)
                    {
                        quantytyyy += item1.quantity;
                    }
                    ViewBag.quantity = quantytyyy;
                }
                return View(list);
            }
            public RedirectToRouteResult updateitem(long P_SanPhamID, int P_quantity)
            {
                var cart = Session[SessionCart];
                var list = (List<Cart_item>)cart;
                Cart_item itemSua = list.FirstOrDefault(m => m.product.ID == P_SanPhamID);
                if (itemSua != null)
                {
                    itemSua.quantity = P_quantity;
                }
                return RedirectToAction("Index");
            }
            public RedirectToRouteResult deleteitem(long productID)
            {
                var cart = Session[SessionCart];
                var list = (List<Cart_item>)cart;

                Cart_item itemXoa = list.FirstOrDefault(m => m.product.ID == productID);
                if (itemXoa != null)
                {
                    list.Remove(itemXoa);
                }
            Message.set_flash("Cập nhật thành công", "success");
            return RedirectToAction("Index");
            }
            public RedirectToRouteResult Additem(long productID, int quantity , String time)
            {
                var item = new Cart_item();
                movies product = db.movies.Find(productID);
                var cart = Session[SessionCart];
                if (cart != null)
                {
                    var list = (List<Cart_item>)cart;
                    if (list.Exists(m => m.product.ID == productID && m.time ==time ))
                    {
                        int quantity1 = 0;
                        foreach (var item1 in list)
                        {
                            if (item1.product.ID == productID && item1.time == time )
                            {
                                item1.quantity += quantity;
                                quantity1 = item1.quantity;
                            }
                        }
                        int priceTotol = 0;

                        int price = 0;
                        foreach (var item1 in list)
                        {
                            int temp = (int)item1.product.price * (int)item1.quantity;
                            priceTotol += temp;

                            price = (int)item1.product.price;
                        }
                    Message.set_flash("Thêm thành công", "success");
                    return RedirectToAction("Index");

                    }
                    else
                    {
                        item.product = product;
                        item.quantity = quantity;
                        item.time = time;
                        item.day = DateTime.Now;
                        list.Add(item);
                        item.countCart = list.Count();
                        item.meThod = "cartExist";
                        int priceTotol = 0;
                        foreach (var item1 in list)
                        {
                            int temp = (int)item1.product.price * (int)item1.quantity;
                            priceTotol += temp;
                        }
                        item.priceTotal = priceTotol;
                    Message.set_flash("Thêm thành công", "success");
                    return RedirectToAction("Index");
                    }
                }
                else
                {
                    item.product = product;
                    item.quantity = quantity;
                    item.time = time;
                    item.day = DateTime.Now;
                    item.meThod = "cartEmpty";
                    item.countCart = 1;
                    item.priceTotal = (int)product.price;
                    var list = new List<Cart_item>();
                    list.Add(item);
                    Session[SessionCart] = list;

                }
            Message.set_flash("Thêm thành công", "success");
            return RedirectToAction("Index");
            }
        }
    }

WebBanVeXemPhim/Webanvexemphim/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webanvexemphim.Models;
namespace Webanvexemphim.Controllers
{
    public class CheckoutController : Controller
    {
        private const string SessionCart = "SessionCart";
        private Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
        // GET: Checkout
        [HttpPost]
        public ActionResult  Thanh_toan(order order)
        {
            var cart = Session[SessionCart];

            var list = new List<Cart_item>();
            if (cart != null)
            {
                list = (List<Cart_item>)cart;
            }
            else
            {
                ViewBag.error = "Vui lòng thêm sản phẩm vào giỏ hàng";
                return View("index");
            }
            Random rand = new Random((int)DateTime.Now.Ticks);
            int RandomNumber;
            RandomNumber = rand.Next(100, 100000);
            if (ModelState.IsValid)
            {
                order.code = RandomNumber.ToString();
                order.userid = 1;
                order.created_ate = DateTime.Now;
                order.status = 2;
                order.userid = 1;
                order.exportdate = DateTime.Now;
                db.Orders.Add(order);
                db.SaveChanges();
                int lastid = order.ID;
                var orderLast = db.Orders.Find(lastid);
                ordersdetail orderdetail = new ordersdetail();
                foreach (var item in list)
                {
                    float price = 0;
                    price = (float)item.product.price * (int)item.quantity;                
                    orderdetail.orderid = order.ID;
                    orderdetail.productid = item.product.ID;
                    orderdetail.priceSale = (int)item.product.price;
                    orderdetail.day = item.day;
                    orderdetail.time = item.time;
                    orderdetail.price = item.product.price;
                    orderdetail.quantity = item.quantity;
                    orderdetail.amount = price;
                    db.Ordersdetails.Add(orderdetail);
                    db.SaveChanges();
                }
                ViewBag.cart = (List<Cart_item>)cart;
                Session["SessionCart"] = null;
                var listProductOrder = db.Ordersdetails.Where(m => m.orderid == order.ID);
                return View("oderComplete", orderLast);
            }
            ViewBag.error = "Đặt hàng thất bại";
            return View("index");

        }
        public ActionResult subnameProduct(int id)
        {
            var list = db.movies.Find(id);
            return View("_subproductOrdersuccess", list);

        }
        public ActionResult productDetailCheckOut(int orderId)
        {
            var list = db.Ordersdetails.Where(m => m.orderid == orderId).ToList();
            return View("_productDetailCheckOut", list);

        }
    }
}

WebBanVeXemPhim/Webanvexemphim/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webanvexemphim.Controllers
{
    public class ModulesController : Controller
    {
        private Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
        // GET: nơi chứa các layout chính của web header/footer
        public ActionResult _header()
        {
            return View("_header");
        }
        public ActionResult _mainmenu()
        {
            var listParentCate = db.menus.Where(m => m.status == 1 && m.parentid == 0).OrderBy(m => m.orders).ToList();
            return View("_mainmenu", listParentCate);
        }
        public ActionResult _footer()
        {
            return View("_footer");
        }

        public ActionResult submainmenu(int id)
        {
            ViewBag.mainmenuitem = db.menus.Find(id);
            var list = db.menus.Where(m => m.status == 1).Where(m => m.parentid == id)
                .OrderBy(m => m.orders);
            if (list.Count() != 0)
            {
                return View("_submainmenu1", list);
            }
            else
            {
                return View("_submainmenu2");
            }

        }

    }
}

WebBanVeXemPhim/Webanvexemphim/Views/Cart/Index.cshtml
@model IEnumerable<Webanvexemphim.Models.Cart_item>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "postDetaail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Action("_Header", "Modules")
<main class="cart-page-main-block inner-page-sec-padding-bottom">
    <div class="cart_area cart-area-padding  ">
        <div class="container">
            <div class="pt-5">
                <div class="section-pannel ">
                    <div class="grid row">
                        <div class="col-md-10">
                            <form autocomplete="off">
                                <div class="row form-grid">
                                    <div class="col-sm-12">

                                        <p>  Trang Chủ / <span class="text-danger"> Thông tin vé đã đặt  </span> </p>
                                    </div>
                                    @Html.Partial("_MessgeAlert")
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
            <div class="page-section-title">
                <h1>Thông tin vé đã đặt</h1>
            </div>
            <div class="row">
                <div class="col-12">
                    <form action="#" class="">
                        <!-- Cart Table -->
                        <div class="cart-table table-responsive mb--40">
                            <table class="table">
                                <!-- Head Row -->
                                <thead>
                                    <tr>
                                        <th class="pro-remove"></th>
                                        <th class="pro-thumbnail">Ảnh phim</th>
                                        <th class="pro-title">Tên phim</th>
                                        <th class="pro-price">Giá vé</th>
                                        <th class="pro-price">Giờ chiếu</th>
                                        <th class="pro-quantity">Số lượng</th>
                                        <th class="pro-subtotal">Tổng tiền</th>
                                    </tr>
                                </thead>
                                <tbody class="border">
                                    <spam class="text-danger"> @ViewBag.statusCart</spam>
                                    <!-- Product Row -->

                                    @{ float sum = 0;
                                    }
                                    @foreach (var iten in Model)
                                    {
                                        var su1m = iten.product.price * iten.quantity;
                                        sum += (float)su1m;
                                        <tr id="cartItem_@iten.product.ID">
                                            <td class="pro-remove">
                                                <a href="~/Cart/deleteitem?productID=@iten.product.ID"><i class="far fa-trash-alt"></i></a>
                                            </td>
                                            <td class="pro-thumbnail">
                                                <a href="#">
                                                    <img width="30px" src="~/Public/images/@iten.product.img" alt="Product">
                                                </a>
                                            </td>
                                            <td class="pro-title"><a href="#">@iten.product.name</a></td>

                                            <td class="pro-price">

                                                <span class="text-danger">@iten.product.price.ToString("N0") VND  </span>
                                            </td>
                                            <td class="pro-price">

                                                <span class="text-danger"> lúc @iten.time  ngày: @iten.day.ToString("dd/MM/yyyy")</span>
                                            </td>
                                            <td class="pro-quantity">
                                                <div class="pro-qty">
                                                    <div class="count-input-block">
                                                        <p type="number" class=" text-center w-25">@iten.quantity</p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="pro-subtotal"><span class="font-weight-bold">@su1m.ToString("N0") VND</span></td>
                                        </tr>

                                    }

                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
                <!-- Cart Summary -->

                <div class="col-lg-6 col-12 d-flex ">
                    <div class="cart-summary  float-right ">
                        <div class="cart-summary-wrap">
                            <h4><span>Thanh toán</span></h4>
                            <p>Tổng tiền vé <span class="text-primary">@sum.ToString("N0") VND</span></p>
                            <p>Chiết khấu <span class="text-primary">0 VND</span></p>
                            <h2>Tổng tiền thanh toán <span class="text-primary">@sum.ToString("N0") VND</span></h2>
                        </div>
                       
                          
                        </div>

                </div>

                <div class="col-lg-6 col-12  ">
                    @using (Html.BeginForm("Thanh_toan", "Checkout", FormMethod.Post))
                    {
                        <div id="billing-form" class="mb-40">
                            <h4 class="checkout-title p-2">Thông tin đặt vé</h4>
                            <div class="row form-grid">

                                <div class="col-sm-6">
                                    <div class="input-view-flat input-group">
                                        <input class="form-control" name="deliveryname" type="text" placeholder="Tên bạn" required />
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="input-view-flat input-group">
                                        <input class="form-control" name="deliveryemail" type="text" placeholder="Địa chỉ Email" required />
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="input-view-flat input-group">
                                        <input class="form-control" name="deliveryphone" type="text" placeholder="Số điện thoại" required />
                                    </div>
                                </div>
                                <input type="hidden" name="sum" value="@sum" />
                                <div class="col-sm-6">
                                    <div class="input-view-flat input-group">
                                        <input class="form-control" name="deliveryaddress" type="text" placeholder="Địa chỉ " required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <label>Ghi chú</label>
                                    <div class="input-view-flat input-group">

                                        <textarea class="form-control" name="note" type="text" placeholder="ghi chú ">
                                        </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="cart-summary-button pt-2">
                            <button type="submit" class=" w-100 btn-theme btn">Đặt vé</button>

                        </div>
                    }
                </div>
            </div>
    </div>

</main>
<div class="pt-5"></div>
@Html.Action("_footer", "Modules")