WebBanVeXemPhim/Webanvexemphim/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webanvexemphim.Controllers
{
    public class ModulesController : Controller
    {
        private Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
        // GET: nơi chứa các layout chính của web header/footer
        public ActionResult _header()
        {
            return View("_header");
        }
        public ActionResult _mainmenu()
        {
            var listParentCate = db.menus.Where(m => m.status == 1 && m.parentid == 0).OrderBy(m => m.orders).ToList();
            return View("_mainmenu", listParentCate);
        }
        public ActionResult _footer()
        {
            return View("_footer");
        }

        public ActionResult submainmenu(int id)
        {
            ViewBag.mainmenuitem = db.menus.Find(id);
            var list = db.menus.Where(m => m.status == 1).Where(m => m.parentid == id)
                .OrderBy(m => m.orders);
            if (list.Count() != 0)
            {
                return View("_submainmenu1", list);
            }
            else
            {
                return View("_submainmenu2");
            }

        }

    }
}

WebBanVeXemPhim/Webanvexemphim/Controllers/PostCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webanvexemphim.Controllers
{
    public class PostCController : Controller
    {
        private Webanvexemphim.Models.DbConnection db = new Webanvexemphim.Models.DbConnection();
        // GET: PostC
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult postDetaail(string slug)
        {
            var SingleProduct = db.posts.Where(m => m.status == 1 && m.slug == slug).First();
            //ViewBag.category = db.Categorys.Find(SingleProduct.catid);
            return View("postDetaail", SingleProduct);
        }
        public ActionResult post_cate(string slug)
        {
            var singleMovies = db.topics.Where(m=>m.slug == slug).FirstOrDefault();
            ViewBag.nameCate = singleMovies.name.ToString();
            var listMovie = db.posts.Where(m => m.status == 1 && m.topid == singleMovies.ID).ToList();
            return View("post_cate", listMovie);
        }
        public ActionResult _postSugger()
        {
            var singleMovies = db.topics.Where(m => m.status == 1 && m.slug == "thong-tin-phim").FirstOrDefault();
            var listMovie = db.posts.Where(m => m.status == 1 && m.topid == singleMovies.ID).ToList();
            
            return View("_postSugger", listMovie);
        }

    }
}

WebBanVeXemPhim/Webanvexemphim/Views/PostC/_postSugger.cshtml
@model IEnumerable<Webanvexemphim.Models.post>
@foreach (var item in Model)
{
    <div class="article-short-line-entity">
        <a class="entity-preview" href="article-sidebar-right.html">
            <span class="embed-responsive embed-responsive-16by9">
                <img class="embed-responsive-item" src="~/public/images/post/@item.img" alt="" />
            </span>
        </a>
        @{
            string title = item.title;
        }
        <div class="entity-content">
            <h4 class="entity-title">
                <a class="content-link" href="article-sidebar-right.html"></a>
            </h4>
            @if (title.Length > 40)
            {
                <p class="font-weight-bold entity-subtext">@title.Substring(0, 40)...</p>
            }
            else
            {
                <p class="entity-subtext">@title</p>
            }

        </div>
    </div>
}

WebBanVeXemPhim/Webanvexemphim/Views/PostC/postDetaail.cshtml
@model Webanvexemphim.Models.post
@{
    ViewBag.Title = "postDetaail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Action("_Header", "Modules")
<div class="container">
    <div class="pt-5">
        <div class="section-pannel ">
            <div class="grid row">
                <div class="col-md-10">
                    <form autocomplete="off">
                        <div class="row form-grid">
                            <div class="col-sm-12">

                                <p >  Trang Chủ / Chi tiết bài viết / <span class="text-danger"> @Model.title </span> </p>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    <div class="sidebar-container ">
        <div class="content">
            <section class="section-long section-spaced">
                <div class="section-line">
                    <article class="article-tape-entity">

                        <div class="entity-content">
                            <h2 class="entity-title">@Model.title</h2>
                            <div class="entity-category">
                                <a class="content-link" href="news-blocks-sidebar-right.html">comedy</a>,
                                <a class="content-link" href="news-blocks-sidebar-right.html">detective</a>,
                                <a class="content-link" href="news-blocks-sidebar-right.html">sci-fi</a>
                            </div>
                        </div>
                    </article>
                    <div class="section-description">
                        <p>@Html.Raw(Model.detail)</p>
                    </div>

                </div>

                <div class="section-line">
                    <div class="section-head">
                       
                    </div>
                    <form autocomplete="off">
                        <div class="row form-grid">
                            <div class="col-12 col-sm-6">
                                <div class="input-view-flat input-group">
                                    <input class="form-control" name="name" type="text" placeholder="Tên" />
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="input-view-flat input-group">
                                    <input class="form-control" name="email" type="email" placeholder="Email" />
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="input-view-flat input-group">
                                    <textarea class="form-control" name="review" placeholder="Review của bạn"></textarea>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="rating-line">
                                    <label>Xếp hạng:</label>
                                    <div class="form-rating" name="rating">
                                        <input type="radio" id="rating-10" name="rating" value="10" />
                                        <label for="rating-10">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-9" name="rating" value="9" />
                                        <label for="rating-9">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-8" name="rating" value="8" />
                                        <label for="rating-8">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-7" name="rating" value="7" />
                                        <label for="rating-7">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-6" name="rating" value="6" />
                                        <label for="rating-6">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-5" name="rating" value="5" />
                                        <label for="rating-5">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-4" name="rating" value="4" />
                                        <label for="rating-4">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-3" name="rating" value="3" />
                                        <label for="rating-3">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-2" name="rating" value="2" />
                                        <label for="rating-2">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                        <input type="radio" id="rating-1" name="rating" value="1" />
                                        <label for="rating-1">
                                            <span class="rating-active-icon"><i class="fas fa-star"></i></span>
                                            <span class="rating-icon"><i class="far fa-star"></i></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="px-5 btn btn-theme" type="submit">Gửi đi</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
        <div class="sidebar section-long order-lg-last">
            <section class="section-sidebar">
                <div class="section-head">
                    @*<h2 class="section-title text-uppercase">Các bài viết review</h2>*@
                </div>
                @Html.Action("_postSugger", "PostC")

            </section>
            <section class="section-sidebar">
                <div class="section-head">
                    @*<h2 class="section-title text-uppercase">Phim trong tháng</h2>*@
                </div>
                @*<ul class="list-unstyled list-wider list-categories">
                    <li>
                        <a class="content-link text-uppercase" href="#">tháng 8 2020</a>
                    </li>
                    <li>
                        <a class="content-link text-uppercase" href="#">tháng 9 2020</a>
                    </li>
                    <li>
                        <a class="content-link text-uppercase" href="#">tháng 10 2020</a>
                    </li>
                    <li>
                        <a class="content-link text-uppercase" href="#">tháng 11 2020</a>
                    </li>
                </ul>*@
            </section>

        </div>
    </div>
</div>
@Html.Action("_footer", "Modules")

WebBanVeXemPhim/Webanvexemphim/Views/PostC/post_cate.cshtml
@model IEnumerable<Webanvexemphim.Models.post>
@{
    ViewBag.Title = "Tin tức";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Action("_Header", "Modules")
<section class="section-long">
    <div class="container">
        <div class="section-pannel">
            <div class="grid row">
                <div class="col-md-10">
                    <form autocomplete="off">
                        <div class="row form-grid">
                            <div class="col-sm-6 col-lg-3">

                                <p>  Trang Chủ/ <span class="text-danger">@ViewBag.nameCate</span> </p>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-2 my-md-auto d-flex">
                    <span class="info-title d-md-none mr-3">Select view:</span>
                    <ul class="ml-md-auto h5 list-inline">
                        <li class="list-inline-item">
                            <a class="content-link transparent-link" href="movies-blocks.html"><i class="fas fa-th"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a class="content-link transparent-link active" href="movies-list.html"><i class="fas fa-th-list"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        @foreach (var item in Model)
        {
            <article class="movie-line-entity">
                <div class="entity-poster" >
                    <div class="embed-responsive embed-responsive-poster">
                        <div>  <img width="100" height="100" class="embed-responsive-item" src="~/public/images/post/@item.img" alt="" /></div>
                      
                    </div>
                    <div class="d-over bg-theme-lighted collapse animated faster" data-show-class="fadeIn show" data-hide-class="fadeOut show">
                        <div class="entity-play">
                            <a class="action-icon-theme action-icon-bordered rounded-circle"  data-magnific-popup="iframe">
                                <span class="icon-content"><i class="fas fa-play"></i></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="entity-content">
                    <h4 class="entity-title">
                        <a class="content-link text-uppercase" href="~/Chi-tiet-vai-viet/@item.slug">@item.title</a>
                    </h4>
                    <div class="entity-category">
                        <a class="content-link" href="movies-blocks.html">@item.created_at.ToString("dd/MM/yyyy")</a>
                    </div>
                    <div class="entity-category">
                        <a class="content-link" href="movies-blocks.html">Tin Tức</a>
                    </div>
                    <p class="text-short entity-text">
                        @Html.Raw(item.descriptionShort)
                    </p>
                </div>
              
            </article>
        }
    </div>
</section>
@Html.Action("_footer", "Modules")